In [11]:
import numpy as np

list_numbers = [1, 2, 3, 4, 5]  # создание списка с числами
array_numbers = np.array(list_numbers)  # создание массива из списка
print(f'Массив из списка: {array_numbers}')

array_zeros = np.zeros(5)  # создание массива из 5 нулей
print(f'Массив из нулей: {array_zeros}')

array_ones = np.ones(5)  # создание массива из 5 единиц
print(f'Массив из единиц: {array_ones}')

array_range = np.arange(0, 10, 2)  # создание массива со значениями в диапазоне от 0 до 10 с шагом 2
print(f'Массив с arange: {array_range}')

matrix_ones = np.ones((2, 3))  # создание матрицы (он же двумерный массив) из единиц размером 2 строки на 3 столбца
print(f'Матрица (двумерный массив) из единиц:\n{matrix_ones}')

Массив из списка: [1 2 3 4 5]
Массив из нулей: [0. 0. 0. 0. 0.]
Массив из единиц: [1. 1. 1. 1. 1.]
Массив с arange: [0 2 4 6 8]
Матрица (двумерный массив) из единиц:
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # создание матрицы из списка
print(f'Двумерный массив (матрица):\n{matrix}')
print(f'shape - форма массива (размерность): {matrix.shape}')  # использование атрибута shape (размерность массива)
print(f'dtype - тип данных: {matrix.dtype}')  # тип элементов в массиве

Двумерный массив (матрица):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape - форма массива (размерность): (3, 3)
dtype - тип данных: int64


In [20]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])  # создание массива из списка
print(f'Массив: {array}')

print(f'Первый элемент: {array[0]}')  # первый элемент (помним, про индексацию с 0)
print(f'Последний элемент: {array[-1]}')  # последний элемент
print(f'Третий элемент: {array[2]}')  # тертий элемент массива

print(f'Элементы с 2 по 5: {array[1:5]}')  # элементы с 2 по 5
print(f'Первые 4 элемента: {array[:4]}')  # элементы с 1 по 4
print(f'Элементы с шагом 2: {array[::2]}')  # каждый 2 элемент

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # создание матрицы из списка
print(f'\nДвумерный массив:\n{matrix}')
print(f'Элемент из 1 строки 2 столбца: {matrix[0, 1]}')  # элемент из 1 строки 2 столбца
print(f'Вторая строка: {matrix[1, :]}')  # вся вторая строка
print(f'Второй столбец: {matrix[:, 1]}')  # весь второй столбец

Массив: [ 10  20  30  40  50  60  70  80  90 100]
Первый элемент: 10
Последний элемент: 100
Третий элемент: 30
Элементы с 2 по 5: [20 30 40 50]
Первые 4 элемента: [10 20 30 40]
Элементы с шагом 2: [10 30 50 70 90]

Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Элемент из 1 строки 2 столбца: 2
Вторая строка: [4 5 6]
Второй столбец: [2 5 8]


In [21]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(f'Массив a: {a}')
print(f'Массив b: {b}')

print(f'Поэлементное сложение: {a + b}')
print(f'Поэлементное умножение: {a * b}')

print(f'Среднее значение массива a: {np.mean(a)}')  # вычисление средней величины
print(f'Сумма всех элементов массива a: {np.sum(a)}')  # вычисление cуммы всех элементов
print(f'Минимальное значение массива a: {np.min(a)}')  # вычисление минимального значения
print(f'Максимальное значение массива a: {np.max(a)}')  # вычисление максимального значения

Массив a: [1 2 3 4 5]
Массив b: [10 20 30 40 50]
Поэлементное сложение: [11 22 33 44 55]
Поэлементное умножение: [ 10  40  90 160 250]
Среднее значение: 3.0
Сумма всех элементов: 15
Минимальное значение: 1
Максимальное значение: 5
